### ISSUE TITLE
License / Contributions ?

### ISSUE THREAD

**Issue by ThibaultLemaire** [bones-ai/rust-drive-ai#1]
Hey!! What a fun little simulation, I love it!

This has made me want to get back to small neural net sims like this one.

I'd like to use and/or contribute to your code, can I? :)

Also if you need help choosing a license, I'm not an expert but I know a thing or two :)

**Comment by bones-ai** [comment]
Hey, 

I've added a license to the project now, feel free to make any contributions to the project :)

**Comment by ThibaultLemaire** [comment]
Awesome!

Well I have been hacking at it for the past couple of days, so feel free to pick what you like!

https://gitlab.com/ThibaultLemaire/rust-drive-ai

You can open issues here and @ me in them to discuss different things, if you'd like, or we can set up more casual communication channels :)

**Comment by bones-ai** [comment]
That's pretty cool, thanks for sharing the fork (I'll add it to readme when I get some time), 
I'll definitely take a look at all the fixes and updates you've made :+1:
